language: node_js

node_js:
  - "node"
  
before_install:
  - rvm install 2.6.2
  - gem install awesome_bot

before_script:

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then if [ -f temp.md ]; then git diff origin/master -U0 README.md | grep -Pos "(?<=^\+).*" >> temp.md && node tests/test.js temp.md; else (exit 0); fi else node tests/test.js temp.md; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then if [ -f temp.md ]; else (exit 0); fi else awesome_bot temp.md --allow-redirect --skip-save-results; else awesome_bot README.md --allow-redirect --skip-save-results; fi'

notifications:
  email: false

branches:
  only:
  - master