language: node_js

node_js:
  - "node"

before_install:
  - rvm install 2.6.2
  - gem install awesome_bot
  - gem install danger

before_script:

script:
  - git diff master.. --unified=0 README.md | grep --perl-regexp --only-matching --silent "(?<=^\+).*" >> temp.md || (exit 0)
  - node tests/test.js temp.md
  - awesome_bot temp.md --allow-redirect || (exit 0)
  - danger --dangerfile=tests/Dangerfile --verbose

notifications:
  email: false
